---
# file: setup.yml

- name: Setup Host
  hosts: local

  vars:
    enable_debug: true
    playbook: "dotfiles"

  vars_files:
    - vars/config.yml

  roles:
    - role: debug
      when: enable_debug == true
    - role: dotfiles
    - role: vim
