#!/bin/bash

function _check {
  if [ $1 -ne 0 ]; then
    echo "$2 must complete on project $3 before commit"
    exit 1
  fi
}

echo "Running pre-commit hooks"

./scripts/utility go-lint ./...
_check $? "golangci-lint"
