---
# file: roles/common/tasks/main.yml

- name: Setting codespaces from environment
  set_fact: is_codespaces="{{ lookup('env', 'CODESPACES') | default('false', True) }}"

- name: Run common tasks for Arch hosts
  include_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Run common tasks for Debian hosts
  include_tasks: debian.yml
  when: "(ansible_os_family == 'Debian' and hostvars['localhost']['is_codespaces'] == false)"

- name: Run common tasks for macOS hosts
  include_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- name: Run common tasks for Codespaces
  include_tasks: codespaces.yml
  when: "(ansible_os_family == 'Debian' and hostvars['localhost']['is_codespaces'] == true)"

# XXX: things that maybe go somewhere else
- name: Download nodenv
  ansible.builtin.git:
    repo: https://github.com/nodenv/nodenv.git
    dest: "{{ lookup('env', 'HOME') }}/.nodenv"
    update: yes
  become: yes
  become_user: "{{ user }}"
  tags:
    - common
    - node

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.nodenv/bin/nodenv"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/nodenv"
    state: link
  become: yes
  become_user: "{{ user }}"
  tags:
    - common
    - node

- name: Build nodenv dynamic bash extension
  ansible.builtin.command:
    cmd: src/configure && make -C src || true
    chdir: "{{ lookup('env', 'HOME') }}/.nodenv"
  become: yes
  become_user: "{{ user }}"

- name: Create nodenv plugins path
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.nodenv/plugins"
    state: directory
    mode: 0775
    recurse: yes
  become: yes
  become_user: "{{ user }}"

- name: Install nodenv plugins
  ansible.builtin.git:
    repo: "https://github.com/nodenv/{{ item }}.git"
    dest: "{{ lookup('env', 'HOME') }}/.nodenv/plugins/{{ item }}"
    update:
  with_items:
    - node-build
    - nodenv-aliases
  become: yes
  become_user: "{{ user }}"

- name: Check a thing
  ansible.builtin.shell: ls "{{ lookup('env', 'HOME') }}/.local/bin"
  become: yes
  become_user: "{{ user }}"

- name: Check another thing
  debug:
    msg: "{{ lookup('env', 'PATH') }}"
  become: yes
  become_user: "{{ user }}"

- name: Install node v14.17
  ansible.builtin.command: "/home/{{ user }}/.local/bin/nodenv install --skip-existing 14.17.0"
  become: yes
  become_user: "{{ user }}"

- name: Set global node version to v14.17
  ansible.builtin.command: "/home/{{ user }}/.local/bin/nodenv global 14.17.0"
  become: yes
  become_user: "{{ user }}"
